version: "3.5"
services:

  zookeeper-dc1:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper-dc1
    container_name: zookeeper-dc1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker-dc1:
    image: confluentinc/cp-kafka
    hostname: broker-dc1
    container_name: broker-dc1
    depends_on:
      - zookeeper-dc1
    ports:
      - "9091:9091"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-dc1:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-dc1:29091,PLAINTEXT_HOST://localhost:9091'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  broker-dc2:
    image: confluentinc/cp-kafka
    hostname: broker-dc2
    container_name: broker-dc2
    depends_on:
      - zookeeper-dc1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-dc1:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-dc2:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  data-producer:
    image: xutpbiy/data-producer
    ports:
      - 9780:9780
    depends_on:
      - broker-dc1
    environment:
      SERVER_PORT: 9780
      KAFKA_BOOTSTRAP_SERVERS: 'PLAINTEXT://broker-dc1:29091,PLAINTEXT_HOST://localhost:29091'
      APPLICATION_ID: 'data_validator'
    volumes:
      - "./src/main/resources:/docker-entrypoint"

  data-validator-topology-dc1:
    container_name: "data-validator-dc1"
    image: app-data-validate-dc1
    build: .
    ports:
      - 9680:9680
    depends_on:
      - broker-dc1
    environment:
      SERVER_PORT: 9680
      KAFKA_BOOTSTRAP_SERVERS: 'PLAINTEXT://broker-dc1:29091,PLAINTEXT_HOST://localhost:29091'
      APPLICATION_ID: 'data_validator'
      REPLICATION_FACTOR: 1
      STREAMS_THREAD_NUM: 1
      OFFSET_RESET: 'latest'

  data-validator-topology-dc2:
    container_name: "data-validator-dc2"
    image: app-data-validate-dc2
    build: .
    ports:
      - 9681:9681
    depends_on:
      - broker-dc2
    environment:
      SERVER_PORT: 9681
      KAFKA_BOOTSTRAP_SERVERS: 'PLAINTEXT://broker-dc2:29092,PLAINTEXT_HOST://localhost:29092'
      APPLICATION_ID: 'data_validator'
      REPLICATION_FACTOR: 1
      STREAMS_THREAD_NUM: 1
      OFFSET_RESET: 'latest'